version: 1.0
current_profile: default

# Tech stack profiles â€” controls which standards get installed
# Copy to config.local.yml and customize your profile
profiles:
  default:
    stack:
      # Global
      global: true

      # Backend
      backend: true
      # Testing
      testing: true

      # # Backend frameworks
      # fastapi: true
      # django: true
      # rails: true
      # express: true

      # # Databases
      # postgresql: true
      # mysql: true
      # mongodb: true
      # redis: true

      # # Frontend
      # react: true
      # nextjs: true
      # vue: true

      # # Infrastructure
      # nginx: true
      # gunicorn: true
      # uvicorn: true
      # docker: true

      # # Languages
      # python: true
      # ruby: true
      # typescript: true
      # javascript: true

    plan_mode:
      step1_shape_spec: true
      step2_define_spec: true
      step3_scope_tasks: true
      step4_implement_tasks: true
